import { getFirestore, writeBatch, doc } from "firebase/firestore";
import { initializeApp } from "firebase/app";

// Your Firebase config (replace with your actual config)
const firebaseConfig = {
    apiKey: "AIzaSyCyC4uuCLJP4ValGtejVXVm6-BApzMursc",
    authDomain: "biasharas-28854.firebaseapp.com",
    projectId: "biasharas-28854",
    storageBucket: "biasharas-28854.firebasestorage.app",
    messagingSenderId: "370075153998",
    appId: "1:370075153998:web:47bd7e39064eb572f1751f",
    measurementId: "G-CN9L32CGHT"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);

// async function massAddStrategies() {
//   const strategies = [
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1203.59,
//         "date": "2024-10-18T11:02:24.328Z",
//         "profit": -188.36,
//         "transactionId": 1,
//         "type": "sell",
//         "lots": 2.66,
//         "tradingSession": "New York",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1750.66,
//         "date": "2024-10-14T04:33:01.950Z",
//         "profit": 56.75,
//         "transactionId": 2,
//         "type": "sell",
//         "lots": 2.21,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 536.63,
//         "date": "2024-04-21T06:32:59.993Z",
//         "profit": -0.93,
//         "transactionId": 3,
//         "type": "buy",
//         "lots": 2.69,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 826.1,
//         "date": "2024-01-03T11:34:37.658Z",
//         "profit": 263.56,
//         "transactionId": 4,
//         "type": "buy",
//         "lots": 1.54,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1647.06,
//         "date": "2024-02-21T04:07:21.393Z",
//         "profit": 222.47,
//         "transactionId": 5,
//         "type": "sell",
//         "lots": 4.38,
//         "tradingSession": "London",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1401.36,
//         "date": "2024-09-28T08:44:42.288Z",
//         "profit": 157.84,
//         "transactionId": 6,
//         "type": "buy",
//         "lots": 3.48,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Fibonacci Retracement",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1771.9,
//         "date": "2024-09-10T10:48:10.964Z",
//         "profit": 36.62,
//         "transactionId": 7,
//         "type": "buy",
//         "lots": 3.82,
//         "tradingSession": "London",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1714.48,
//         "date": "2024-06-12T10:44:13.813Z",
//         "profit": -268.27,
//         "transactionId": 8,
//         "type": "sell",
//         "lots": 1.85,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1373.06,
//         "date": "2024-05-26T22:57:12.927Z",
//         "profit": -325.21,
//         "transactionId": 9,
//         "type": "sell",
//         "lots": 3.71,
//         "tradingSession": "London",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1694.2,
//         "date": "2024-10-17T19:48:45.505Z",
//         "profit": 484.91,
//         "transactionId": 10,
//         "type": "buy",
//         "lots": 1.6,
//         "tradingSession": "London",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1075.15,
//         "date": "2024-07-24T11:19:55.276Z",
//         "profit": 83.95,
//         "transactionId": 11,
//         "type": "buy",
//         "lots": 0.47,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1413.23,
//         "date": "2024-08-10T21:48:17.259Z",
//         "profit": 27.56,
//         "transactionId": 12,
//         "type": "buy",
//         "lots": 3.61,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 763.14,
//         "date": "2024-01-27T17:21:31.402Z",
//         "profit": -406.46,
//         "transactionId": 13,
//         "type": "sell",
//         "lots": 2.63,
//         "tradingSession": "New York",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1167.75,
//         "date": "2024-01-30T14:22:55.065Z",
//         "profit": 157.82,
//         "transactionId": 14,
//         "type": "buy",
//         "lots": 2.65,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 913.55,
//         "date": "2024-06-30T17:05:41.319Z",
//         "profit": 327.71,
//         "transactionId": 15,
//         "type": "sell",
//         "lots": 0.87,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 626.75,
//         "date": "2024-01-25T05:56:13.035Z",
//         "profit": 174.26,
//         "transactionId": 16,
//         "type": "sell",
//         "lots": 3.71,
//         "tradingSession": "Sydney",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 782.59,
//         "date": "2024-02-11T23:31:42.297Z",
//         "profit": -241.13,
//         "transactionId": 17,
//         "type": "sell",
//         "lots": 0.09,
//         "tradingSession": "New York",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1983.74,
//         "date": "2024-05-13T16:48:14.023Z",
//         "profit": -382.72,
//         "transactionId": 18,
//         "type": "buy",
//         "lots": 4.62,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 665.75,
//         "date": "2024-03-13T15:59:32.680Z",
//         "profit": -427.35,
//         "transactionId": 19,
//         "type": "sell",
//         "lots": 4.89,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1993.5,
//         "date": "2024-12-17T16:36:32.774Z",
//         "profit": -154.08,
//         "transactionId": 20,
//         "type": "sell",
//         "lots": 3.35,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 848.56,
//         "date": "2024-04-12T02:11:12.588Z",
//         "profit": -456.23,
//         "transactionId": 21,
//         "type": "buy",
//         "lots": 3.64,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1145.31,
//         "date": "2024-08-01T15:55:32.127Z",
//         "profit": 329.25,
//         "transactionId": 22,
//         "type": "sell",
//         "lots": 3.76,
//         "tradingSession": "New York",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 918.7,
//         "date": "2024-12-15T14:21:20.193Z",
//         "profit": -43.27,
//         "transactionId": 23,
//         "type": "buy",
//         "lots": 3.22,
//         "tradingSession": "London",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1410.68,
//         "date": "2024-12-15T00:37:14.549Z",
//         "profit": -257.44,
//         "transactionId": 24,
//         "type": "buy",
//         "lots": 4.39,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Fibonacci Retracement",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1629.87,
//         "date": "2024-04-17T02:39:33.928Z",
//         "profit": -164.73,
//         "transactionId": 25,
//         "type": "buy",
//         "lots": 3.4,
//         "tradingSession": "London",
//         "strategyUsed": "Breakout Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1152.56,
//         "date": "2024-07-03T17:43:27.792Z",
//         "profit": 79.34,
//         "transactionId": 26,
//         "type": "sell",
//         "lots": 1.94,
//         "tradingSession": "London",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 955.79,
//         "date": "2024-05-13T21:33:48.614Z",
//         "profit": 421.6,
//         "transactionId": 27,
//         "type": "sell",
//         "lots": 3.05,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1899.74,
//         "date": "2024-01-27T00:46:19.843Z",
//         "profit": 163.07,
//         "transactionId": 28,
//         "type": "sell",
//         "lots": 1.77,
//         "tradingSession": "New York",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1876.81,
//         "date": "2024-04-20T07:39:39.870Z",
//         "profit": 221.95,
//         "transactionId": 29,
//         "type": "buy",
//         "lots": 1.61,
//         "tradingSession": "London",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1831.88,
//         "date": "2024-06-29T05:25:03.289Z",
//         "profit": -430.53,
//         "transactionId": 30,
//         "type": "sell",
//         "lots": 0.12,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1115.1,
//         "date": "2024-12-24T12:51:18.017Z",
//         "profit": -154.74,
//         "transactionId": 31,
//         "type": "sell",
//         "lots": 0.43,
//         "tradingSession": "London",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 758.73,
//         "date": "2024-07-20T10:36:35.879Z",
//         "profit": -117.43,
//         "transactionId": 32,
//         "type": "buy",
//         "lots": 3.18,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1175.09,
//         "date": "2024-08-20T15:56:51.277Z",
//         "profit": 57.27,
//         "transactionId": 33,
//         "type": "buy",
//         "lots": 3.31,
//         "tradingSession": "London",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1811.37,
//         "date": "2024-10-12T03:04:00.877Z",
//         "profit": -498.59,
//         "transactionId": 34,
//         "type": "sell",
//         "lots": 2.9,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1654.05,
//         "date": "2024-03-17T04:53:26.391Z",
//         "profit": -386.93,
//         "transactionId": 35,
//         "type": "sell",
//         "lots": 2.09,
//         "tradingSession": "London",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1048.87,
//         "date": "2024-12-14T12:30:34.903Z",
//         "profit": 203.8,
//         "transactionId": 36,
//         "type": "buy",
//         "lots": 3.46,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Fibonacci Retracement",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1250.01,
//         "date": "2024-09-23T18:14:22.289Z",
//         "profit": -153.92,
//         "transactionId": 37,
//         "type": "sell",
//         "lots": 3.75,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 651.77,
//         "date": "2024-09-08T10:46:28.983Z",
//         "profit": -108.49,
//         "transactionId": 38,
//         "type": "buy",
//         "lots": 1.41,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 627.14,
//         "date": "2024-11-18T13:41:46.628Z",
//         "profit": 43.7,
//         "transactionId": 39,
//         "type": "sell",
//         "lots": 3.17,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Fibonacci Retracement",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1453.18,
//         "date": "2024-11-23T14:01:33.646Z",
//         "profit": 285.36,
//         "transactionId": 40,
//         "type": "sell",
//         "lots": 0.94,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1757.48,
//         "date": "2024-06-20T12:17:11.002Z",
//         "profit": 446.03,
//         "transactionId": 41,
//         "type": "buy",
//         "lots": 3.47,
//         "tradingSession": "New York",
//         "strategyUsed": "Breakout Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1750.95,
//         "date": "2024-11-13T17:16:10.874Z",
//         "profit": 269.65,
//         "transactionId": 42,
//         "type": "buy",
//         "lots": 2.2,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1390.23,
//         "date": "2024-02-27T08:12:19.419Z",
//         "profit": -48.5,
//         "transactionId": 43,
//         "type": "buy",
//         "lots": 3.34,
//         "tradingSession": "Sydney",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1899.31,
//         "date": "2024-01-24T00:10:14.628Z",
//         "profit": -490.56,
//         "transactionId": 44,
//         "type": "buy",
//         "lots": 0.24,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 987.16,
//         "date": "2024-08-24T01:09:03.834Z",
//         "profit": -368.27,
//         "transactionId": 45,
//         "type": "sell",
//         "lots": 0.13,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1532.01,
//         "date": "2024-08-31T06:44:27.490Z",
//         "profit": -262.07,
//         "transactionId": 46,
//         "type": "sell",
//         "lots": 2.05,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1090.54,
//         "date": "2024-02-26T10:31:43.666Z",
//         "profit": 283.09,
//         "transactionId": 47,
//         "type": "sell",
//         "lots": 2.84,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1938.1,
//         "date": "2024-02-20T16:06:31.916Z",
//         "profit": 319.04,
//         "transactionId": 48,
//         "type": "buy",
//         "lots": 0.93,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 807.23,
//         "date": "2024-11-01T08:34:48.064Z",
//         "profit": -292.41,
//         "transactionId": 49,
//         "type": "sell",
//         "lots": 1.21,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1505,
//         "date": "2024-11-25T09:13:10.211Z",
//         "profit": 118.6,
//         "transactionId": 50,
//         "type": "sell",
//         "lots": 0.99,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 975.96,
//         "date": "2024-10-22T23:59:19.914Z",
//         "profit": -222.1,
//         "transactionId": 51,
//         "type": "sell",
//         "lots": 3.21,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Momentum Breakout",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1832.75,
//         "date": "2024-04-10T09:59:15.030Z",
//         "profit": -487.27,
//         "transactionId": 52,
//         "type": "sell",
//         "lots": 0.5,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 841.8,
//         "date": "2024-02-13T21:17:54.207Z",
//         "profit": -65.61,
//         "transactionId": 53,
//         "type": "buy",
//         "lots": 1.3,
//         "tradingSession": "Sydney",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1774.9,
//         "date": "2024-07-28T04:22:16.882Z",
//         "profit": 94.01,
//         "transactionId": 54,
//         "type": "buy",
//         "lots": 4.61,
//         "tradingSession": "New York",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 520.01,
//         "date": "2024-07-27T04:20:05.990Z",
//         "profit": -411.22,
//         "transactionId": 55,
//         "type": "sell",
//         "lots": 0.34,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1051.79,
//         "date": "2024-07-01T08:20:27.023Z",
//         "profit": 92.53,
//         "transactionId": 56,
//         "type": "sell",
//         "lots": 3.33,
//         "tradingSession": "New York",
//         "strategyUsed": "Breakout Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1042.35,
//         "date": "2024-04-15T14:55:52.506Z",
//         "profit": 268.82,
//         "transactionId": 57,
//         "type": "sell",
//         "lots": 0.62,
//         "tradingSession": "London",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 684.51,
//         "date": "2024-11-11T22:38:01.630Z",
//         "profit": 210.96,
//         "transactionId": 58,
//         "type": "buy",
//         "lots": 2.99,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1475.65,
//         "date": "2024-12-13T01:47:38.561Z",
//         "profit": 174.02,
//         "transactionId": 59,
//         "type": "sell",
//         "lots": 4.17,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1241.1,
//         "date": "2024-04-13T03:52:41.539Z",
//         "profit": 7.75,
//         "transactionId": 60,
//         "type": "buy",
//         "lots": 0.87,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 684.51,
//         "date": "2024-09-17T14:14:58.746Z",
//         "profit": 460.89,
//         "transactionId": 61,
//         "type": "sell",
//         "lots": 4.78,
//         "tradingSession": "London",
//         "strategyUsed": "Momentum Breakout",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 689.57,
//         "date": "2024-07-13T06:40:21.587Z",
//         "profit": -441.43,
//         "transactionId": 62,
//         "type": "sell",
//         "lots": 1.63,
//         "tradingSession": "London",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1366.2,
//         "date": "2024-01-04T16:37:43.844Z",
//         "profit": 314.52,
//         "transactionId": 63,
//         "type": "sell",
//         "lots": 2.08,
//         "tradingSession": "London",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1310.69,
//         "date": "2024-07-01T15:01:51.941Z",
//         "profit": 168.57,
//         "transactionId": 64,
//         "type": "sell",
//         "lots": 3.02,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 973.55,
//         "date": "2024-09-02T22:10:48.969Z",
//         "profit": 185.7,
//         "transactionId": 65,
//         "type": "sell",
//         "lots": 4.25,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1496.69,
//         "date": "2024-07-06T02:18:51.606Z",
//         "profit": -224.35,
//         "transactionId": 66,
//         "type": "buy",
//         "lots": 0.68,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 630.83,
//         "date": "2024-09-22T05:02:11.255Z",
//         "profit": -474.48,
//         "transactionId": 67,
//         "type": "buy",
//         "lots": 4.31,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1694.59,
//         "date": "2024-09-06T02:49:49.832Z",
//         "profit": 154.65,
//         "transactionId": 68,
//         "type": "sell",
//         "lots": 1.81,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1463.5,
//         "date": "2024-12-20T03:52:31.699Z",
//         "profit": -303.27,
//         "transactionId": 69,
//         "type": "sell",
//         "lots": 0.05,
//         "tradingSession": "London",
//         "strategyUsed": "Momentum Breakout",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1414.97,
//         "date": "2024-07-11T02:35:29.691Z",
//         "profit": 3.7,
//         "transactionId": 70,
//         "type": "buy",
//         "lots": 3.68,
//         "tradingSession": "London",
//         "strategyUsed": "Breakout Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1093.51,
//         "date": "2024-06-21T19:54:50.914Z",
//         "profit": 473.52,
//         "transactionId": 71,
//         "type": "buy",
//         "lots": 2.71,
//         "tradingSession": "London",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1408.65,
//         "date": "2024-03-02T02:41:37.378Z",
//         "profit": -382.67,
//         "transactionId": 72,
//         "type": "buy",
//         "lots": 1.3,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Breakout Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1406.36,
//         "date": "2024-09-17T12:39:12.319Z",
//         "profit": -463.41,
//         "transactionId": 73,
//         "type": "buy",
//         "lots": 1.88,
//         "tradingSession": "New York",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 949.76,
//         "date": "2024-11-20T23:33:36.345Z",
//         "profit": 215.92,
//         "transactionId": 74,
//         "type": "buy",
//         "lots": 4.23,
//         "tradingSession": "London",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 1366.86,
//         "date": "2024-06-20T04:51:11.304Z",
//         "profit": 404.12,
//         "transactionId": 75,
//         "type": "buy",
//         "lots": 3.78,
//         "tradingSession": "London",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1847.23,
//         "date": "2024-04-09T22:04:19.558Z",
//         "profit": -482.63,
//         "transactionId": 76,
//         "type": "buy",
//         "lots": 3.82,
//         "tradingSession": "New York",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 797.58,
//         "date": "2024-06-21T15:58:42.207Z",
//         "profit": 129.71,
//         "transactionId": 77,
//         "type": "buy",
//         "lots": 3.27,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1729.7,
//         "date": "2024-01-19T03:46:35.691Z",
//         "profit": 141.11,
//         "transactionId": 78,
//         "type": "buy",
//         "lots": 1.93,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1001.5,
//         "date": "2024-04-06T20:01:39.075Z",
//         "profit": -210.8,
//         "transactionId": 79,
//         "type": "buy",
//         "lots": 2,
//         "tradingSession": "New York",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 1314.17,
//         "date": "2024-06-23T04:55:22.494Z",
//         "profit": 384.67,
//         "transactionId": 80,
//         "type": "buy",
//         "lots": 1.44,
//         "tradingSession": "London",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1746.29,
//         "date": "2024-06-30T04:13:05.766Z",
//         "profit": 414.92,
//         "transactionId": 81,
//         "type": "buy",
//         "lots": 4.19,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Momentum Breakout",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 883.79,
//         "date": "2024-12-31T01:34:51.133Z",
//         "profit": 233.73,
//         "transactionId": 82,
//         "type": "sell",
//         "lots": 2.86,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 630.21,
//         "date": "2024-11-02T18:33:08.715Z",
//         "profit": 328.09,
//         "transactionId": 83,
//         "type": "buy",
//         "lots": 1.72,
//         "tradingSession": "New York",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1840.33,
//         "date": "2024-05-05T12:35:17.398Z",
//         "profit": 269.84,
//         "transactionId": 84,
//         "type": "sell",
//         "lots": 4.77,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 876.23,
//         "date": "2024-10-31T23:57:17.333Z",
//         "profit": -412.62,
//         "transactionId": 85,
//         "type": "sell",
//         "lots": 1.53,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1307.5,
//         "date": "2024-02-10T14:49:40.952Z",
//         "profit": -43.1,
//         "transactionId": 86,
//         "type": "sell",
//         "lots": 4.92,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 614.36,
//         "date": "2024-11-28T16:47:09.240Z",
//         "profit": 309,
//         "transactionId": 87,
//         "type": "sell",
//         "lots": 0.79,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1288.51,
//         "date": "2024-12-18T07:18:21.797Z",
//         "profit": 21.28,
//         "transactionId": 88,
//         "type": "sell",
//         "lots": 0.41,
//         "tradingSession": "London",
//         "strategyUsed": "Pivot Point Scalping",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1432.5,
//         "date": "2024-02-14T04:21:34.666Z",
//         "profit": 59.18,
//         "transactionId": 89,
//         "type": "buy",
//         "lots": 1.43,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1371.3,
//         "date": "2024-12-05T23:37:53.859Z",
//         "profit": -117.68,
//         "transactionId": 90,
//         "type": "sell",
//         "lots": 1.36,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "Trend Following with RSI",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1456.78,
//         "date": "2024-08-26T16:01:56.819Z",
//         "profit": 346.34,
//         "transactionId": 91,
//         "type": "sell",
//         "lots": 2.66,
//         "tradingSession": "London",
//         "strategyUsed": "Scalping with Moving Averages",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/JPY",
//         "amountRisked": 1129.63,
//         "date": "2024-06-08T20:56:34.962Z",
//         "profit": -251.6,
//         "transactionId": 92,
//         "type": "buy",
//         "lots": 2.74,
//         "tradingSession": "New York",
//         "strategyUsed": "Mean Reversion Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "EUR/USD",
//         "amountRisked": 725.04,
//         "date": "2024-04-29T10:32:09.271Z",
//         "profit": 230.94,
//         "transactionId": 93,
//         "type": "sell",
//         "lots": 1.12,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "AUD/USD",
//         "amountRisked": 1519.78,
//         "date": "2024-02-15T23:38:28.780Z",
//         "profit": -2.21,
//         "transactionId": 94,
//         "type": "buy",
//         "lots": 3.94,
//         "tradingSession": "London",
//         "strategyUsed": "News Trading Strategy",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1457.52,
//         "date": "2024-02-01T22:46:53.234Z",
//         "profit": 438.35,
//         "transactionId": 95,
//         "type": "buy",
//         "lots": 0.45,
//         "tradingSession": "New York",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 684.23,
//         "date": "2024-07-11T02:54:45.779Z",
//         "profit": -15.34,
//         "transactionId": 96,
//         "type": "buy",
//         "lots": 1.42,
//         "tradingSession": "London",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "NZD/USD",
//         "amountRisked": 1706.35,
//         "date": "2024-06-29T06:40:16.522Z",
//         "profit": 273.21,
//         "transactionId": 97,
//         "type": "sell",
//         "lots": 3.3,
//         "tradingSession": "New York",
//         "strategyUsed": "Supply and Demand Zones",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CHF",
//         "amountRisked": 1267.2,
//         "date": "2024-04-09T18:20:23.243Z",
//         "profit": -421.77,
//         "transactionId": 98,
//         "type": "buy",
//         "lots": 4.16,
//         "tradingSession": "Sydney",
//         "strategyUsed": "Price Action Reversal",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "GBP/USD",
//         "amountRisked": 1125.87,
//         "date": "2024-12-02T23:54:00.509Z",
//         "profit": 256.9,
//         "transactionId": 99,
//         "type": "buy",
//         "lots": 1.8,
//         "tradingSession": "Tokyo",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     },
//     {
//         "currencyPair": "USD/CAD",
//         "amountRisked": 676.17,
//         "date": "2024-05-03T00:33:02.916Z",
//         "profit": 350.23,
//         "transactionId": 100,
//         "type": "buy",
//         "lots": 1.14,
//         "tradingSession": "Sydney",
//         "strategyUsed": "none",
//         "notes": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
//     }
// ];

//   const batch = writeBatch(db);

//   strategies.forEach((strategy) => {
//     const docRef = doc(db, "trades", `${strategy.transactionId}`);
//     batch.set(docRef, strategy);
//   });

//   await batch.commit();
//   console.log("All strategies have been added!");
// }

// massAddStrategies();
